### ISSUE TITLE
Question about (engine property) in the package.json file

### ISSUE THREAD

**Issue by rzkhosroshahi** [testing-library/vue-testing-library#129]
Hello
I have a question
Why did you add engine property in the package.json file? I have an issue with this because it makes an error in my ci/cd. that issue is my node engine version is not compatible whit engine that you added in package.json file and pipeline break up.

**Comment by afontcu** [comment]
Hi!

What node version is your CI/CD pipeline running on?

**Comment by rzkhosroshahi** [comment]
Hey. its 8 version

**Comment by afontcu** [comment]
Then that's the reason 😄 In [v5.0](https://github.com/testing-library/vue-testing-library/releases/tag/v5.0.0) we dropped support for Node 8, since it is out of LTS and we updated [DOM Testing Library](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0).

I guess you'd need to update your CI to support LTS node versions!

I'm closing this, but thanks for filling this in!
Have a great week 😃
