### ISSUE TITLE
Does anybody have an idea of how can I test a component that used portal?

### ISSUE THREAD

**Issue by rzkhosroshahi** [testing-library/vue-testing-library#135]
Hello.
I was trying to test a component that used [portal-vue](https://github.com/LinusBorg/portal-vue) package. My issue is how can I ensure that a component inside the portal after clicking on something, it's rendered or exist.

**Comment by afontcu** [comment]
Hi! Haven't used portal-vue before, fancy to open up a PR to set an example in this repo? 🤗 

I guess you'll need 2 things: 1 to register portal-vue as a plugin:
```js
import PortalVue from 'portal-vue'

test('...', () => {
  const {} = render(MyComp, {}, vue => vue.use(PortalVue))
})
```

and 2 to make sure you render the `destination` node in a custom `container` or `baseElement`. Again, I'm wild guessing since I haven't use it before :)

**Comment by afontcu** [comment]
@rzkhosroshahi does #136 help you? 🤗

**Comment by rzkhosroshahi** [comment]
> @rzkhosroshahi does #136 help you? 🤗

Yes, thanks. it's really helpful ☺️. But in many real-world usages of the portal, the target portal there is not on the same component, so I think we need a component to wrap portal target and make sure this component renders the portal component.
