### ISSUE TITLE
Drag & Drop fireEvents are not working

### ISSUE THREAD

**Issue by nchauhan-ee** [testing-library/vue-testing-library#145]
**Describe the bug**
Drag & drop events are not working when using with https://github.com/SortableJS/Vue.Draggable

**To Reproduce**
I created a git repo to reproduce this issue:
https://github.com/nchauhan-ee/sortable/blob/master/tests/unit/App.spec.js

**Expected behavior**

Drag & Drop to be working

**Related information:**

- `@testing-library/vue` version: `^5.0.3`
- `Vue` version: `^2.6.11`
- `node` version: `v12.13.1`
- `yarn` version: `1.21.0`

Relevant code or config (if any)

```javascript
   render(App);
    const dragElement = screen.getByTestId("Jean");
    const dropZone = screen.getByTestId("John");

    await fireEvent.dragStart(dragElement);
    await fireEvent.dragEnter(dropZone);
    await fireEvent.drop(dropZone);
    await fireEvent.dragLeave(dropZone);
    await fireEvent.dragEnd(dragElement);

    screen.debug();
```

Above, I was expecting the DOM to be updated with the sorted HTML.

**Comment by cilice** [comment]
@nchauhan-ee 
It's not really a testing library problem, it's more of a `jsdom` problem.

Dragging things is a bit weird with `jsdom`, since the generated events have no coordinates and all dom elements have no layout like width, since `jsdom` doesn't implement it.
I was able to find a cypress test in a PR that got closed that actually demos dragging with vuedraggable: https://github.com/appology/cypress-example-recipes/blob/0472464cd5363c20a6c75c28dff270bafae97466/examples/testing-dom__sortablejs_vue/cypress/support/sortable.js

```js
    await fireEvent.mouseDown(dragElement, { which: 1, button: 0 });
    await fireEvent.dragStart(dragElement);
    await fireEvent.dragOver(dropZone);
    await fireEvent.drop(dropZone);
    await fireEvent.mouseUp(dropZone, { which: 1, button: 0 });
```

This actually had some effect on the DOM:
```html
<div
                class="list-group-item sortable-drag"
                data-testid="Jean"
                draggable="false"
                style=""
              >

            Jean

              </div>
```

If I place the `screen.debug()` right after the `fireevent.dragOver` it shows that it actually is starting to drag the thing:
```html
<div
                class="list-group-item sortable-chosen sortable-drag"
                data-testid="Jean"
                draggable="true"
                style="will-change: all; transform: translateZ(0);"
              >

            Jean

              </div>
```

That's all I achieved there without going deeper, cypress has some special helpers and a real browser with boxes that have a width and height.

**Comment by nchauhan-ee** [comment]
In that case I guess I'll have to fall back to vue-test utils just to test the JS Method `onDragEnd` event.

**Comment by Erod-star** [comment]
Thanks for the help!
