### ISSUE TITLE
Drop Node 10 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/vue-testing-library#231]
Because it's [EOL](https://nodejs.org/en/about/releases).

**Comment by afontcu** [comment]
Even though this is a breaking change, and given the fact that `6.x` version range is reserved to support to Vue 3 (see https://github.com/testing-library/vue-testing-library/issues/176), I think we should merge this one as a `chore: ` so no version is issued, or maybe as a `fix: ` so people can get a new version and handle any potential breaking change due to using node 10 (unlikely, I guess).

Thoughts?

**Comment by MichaelDeBoey** [comment]
I would merge it together with Vue 3 support

**Comment by afontcu** [comment]
Yeah, why not! I'll go ahead and change the base branch from the PR now

**Comment by afontcu** [comment]
fixed in https://github.com/testing-library/vue-testing-library/pull/243
