### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by afontcu** [testing-library/vue-testing-library#40]
Hi! I was wondering if there's any kind of roadmap for VTL to work on.

Not (only) in terms of adding features (not sure the API surface should grow that much!), but also regarding the repo itself, and even "marketing".

I have some ideas I'd be willing to work on:

- Add Prettier to the repo.
- Run checks on every PR - Run tests, code coverage variations.
- Fix coveralls integration/badge.
- Add typings _(can't really help on that lol)_.
- Improve explanations on tests _(by adding comments, for instance)_.
- Add more examples _(it'd be great if we could decide if we are showcasing major use cases, or something big is missing)_.
- Explain how to create a Custom Render.
- Provide guides to integrate VTL with @vue/cli and Nuxt.
- Allow [user-event](https://github.com/testing-library/user-event) to work with Vue _(some things need fixing: https://github.com/testing-library/user-event/issues/119)_.
- Write/Curate content on "VTL 101" or even advanced patterns.
- ...

Let me know your thoughts on this :) I'm sure you have other interesting ideas that might be more interesting to work on.

Also I'm not sure what's the best way of organizing those ideas - Maybe using the Projects feature from GitHub?

**Comment by dfcook** [comment]
Hi, I must admit that the basis for this project was simply some "What-if" thinking on my part when I saw Kent's work on RTL. I haven't had a roadmap in mind and, as I'm currently using React for work, am probably not the best person to guide the project forward on a more ambitious roadmap.

One of the things that I've always had in the back of my mind however is that it is built on top of vue-test-utils. I liken this to building RTL on top of enzyme and I'd like to change render so that it mounts the vue components in an entirely different way.

All of your other thoughts sound very sensible and good to haves.

**Comment by afontcu** [comment]
No worries! I feel like working on the library, so I might be submitting more PRs 😄 Some things might require your intervention, thou (such as integrations). Hope I don't bother you too much!


Regarding rendering in an entirely different way, what would you like to change? Is there any limitation you encountered while working with vue-test-utils?

**Comment by dfcook** [comment]
No limitation, it just feels like there's a dependency there that we shouldn't necessarily need.
