### ISSUE TITLE
Wrapper from vue-test-utils not exposed?

### ISSUE THREAD

**Issue by gchenglevi** [testing-library/vue-testing-library#46]
Hi, I wanted to call something like `wrapper.isVueInstance()` like I would with `vue-test-utils`. Looks like this wouldn't be possible in this library? Thanks.

**Comment by afontcu** [comment]
Hi! 👋 and thanks for your question.

Vue Testing Library tries to follow the [Testing Library Guiding Principle](https://testing-library.com/docs/guiding-principles). Since we are trying to focus on **rendering components instead of dealing with component instances**, it wouldn't make much sense to provide a tool that helps testing you the exact opposite - if a given wrapper is a Vue instance.

That's the reason behind not providing such method.

In Vue Testing Library world, I'd just render the component and assert that the "initial state" is already there - the default strings, values, and so on.

Hope I helped!

**Comment by gchenglevi** [comment]
Ah okay, so my use case is asserting that for my dumb component that an event is emitted on a certain click. Would you say it is good practice to mix tests importing `mount` from `vue-test-utils` and tests with this library in the same component test file?

**Comment by afontcu** [comment]
Check out the [simple button test example](https://github.com/testing-library/vue-testing-library/blob/master/tests/__tests__/simple-button.js), because it looks quite similar to your use case:

1. render the component (I'd go with Vue Testing Library `render()`)
2. get the clickable element
3. fire a click event
4. assert the event was emitted


hope it helps!

**Comment by gchenglevi** [comment]
Oh thanks! I missed the `emitted` method. However, if there would be other cases in the future where I wanted to use a method that isn't exposed, it sounds like it wouldn't be good practice to mix the two libraries.

**Comment by afontcu** [comment]
VTL exposes a `render()` method that contains DOM Testing Library queries + some vue-test-utils methods too: https://testing-library.com/docs/vue-testing-library/api So, in theory, you _are_ mixing both libraris.

The idea is that by using VTL you get the tools to test your components far from implementation details, so if you feel the urge to use a non-exposed method, I believe you'll find an available one that suits your needs. If not, let us know! ;)

Thanks for your questions! Feel free to open up another issue if anything is unclear while using VTL 😄

**Comment by Blindpupil** [comment]
In my case the component expects data from the store in deeply nested modules. I want to access the vm to set the store data that I need. I can do it via the options parameter when the data is in the root, but I'm having a lot of issues making it work when the data is in a deeply nested module
